const PROMOTIONS = {
  "promocionesComida": [
    {
      "Promocion": "2x1 Jumbo",
      "Categoria": "Alimentos",
      "Descripcion": "2 x 1 en Refrescos Jumbo",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.09.2025",
      "VigenciaFin": "30.09.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "2 Refrescos Jumbo",
      "PrecioFull": 184,
      "PorcentajeDescuento": -0.5,
      "PrecioDescuento": 92,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 Frappes x $120",
      "Categoria": "Alimentos",
      "Descripcion": "2 frappes grandes x $120",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.09.2025",
      "VigenciaFin": "30.09.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "2 Frappes grandes",
      "PrecioFull": 184,
      "PorcentajeDescuento": -0.34782608695652173,
      "PrecioDescuento": 120,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Maxicombo Micha Mix x $340",
      "Categoria": "Alimentos",
      "Descripcion": "1 Maxicombo Micha Mix x $340",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.09.2025",
      "VigenciaFin": "30.09.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Maxicombo Micha Mix",
      "PrecioFull": 486,
      "PorcentajeDescuento": -0.3004115226337448,
      "PrecioDescuento": 340,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Combo bagui en pareja x $319",
      "Categoria": "Alimentos",
      "Descripcion": "1 Combo bagui en pareja x $319",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.09.2025",
      "VigenciaFin": "30.09.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Combo bagui en pareja",
      "PrecioFull": 478,
      "PorcentajeDescuento": -0.33263598326359833,
      "PrecioDescuento": 319,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Comboleto 2",
      "Categoria": "Comboletos",
      "Descripcion": "2 boletos de taquilla + CB Nachos en pareja (1 Pal, 2 Ref Jumb, 1 Nachos) x $327",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.09.2025",
      "VigenciaFin": "30.09.2025",
      "Boletos": 2,
      "AlimentosIncluidos": "1 CB Nachos en pareja",
      "PrecioFull": 433,
      "PorcentajeDescuento": -0.24480369515011546,
      "PrecioDescuento": 327,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Comboleto 3",
      "Categoria": "Comboletos",
      "Descripcion": "3 boletos de taquilla + Maxicombo grupo chatbot (2 pal jum, 3 ref jumb) x  $435",
      "PersonasObjetivo": 3,
      "VigenciaInicio": "01.09.2025",
      "VigenciaFin": "30.09.2025",
      "Boletos": 3,
      "AlimentosIncluidos": "1 Maxicombo",
      "PrecioFull": 533,
      "PorcentajeDescuento": -0.1838649155722326,
      "PrecioDescuento": 435,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 M&Ms Mega x $85",
      "Categoria": "Alimentos",
      "Descripcion": "2 M&Ms Mega x $85",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.10.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "2 M&Ms Mega",
      "PrecioFull": 170,
      "PorcentajeDescuento": -0.5,
      "PrecioDescuento": 85,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 baguis x $150",
      "Categoria": "Alimentos",
      "Descripcion": "2 baguis x $150",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.10.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "2 baguis",
      "PrecioFull": 280,
      "PorcentajeDescuento": -0.4642857142857143,
      "PrecioDescuento": 150,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Maxicombo Familiar x $320",
      "Categoria": "Alimentos",
      "Descripcion": "1 Maxicombo Familiar x $320",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.10.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Maxicombo Familiar",
      "PrecioFull": 463,
      "PorcentajeDescuento": -0.3088552915766739,
      "PrecioDescuento": 320,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Combo crepa en pareja x $260",
      "Categoria": "Alimentos",
      "Descripcion": "1 Combo crepa en pareja x $260",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.10.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Combo crepa en pareja",
      "PrecioFull": 320,
      "PorcentajeDescuento": -0.1875,
      "PrecioDescuento": 260,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Comboleto 2",
      "Categoria": "Comboletos",
      "Descripcion": "2 boletos de taquilla + Nachos en pareja (1 Pal, 2 Ref Jumb, 1 Nachos) x $327",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.10.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 2,
      "AlimentosIncluidos": "1 CB Nachos en pareja",
      "PrecioFull": 433,
      "PorcentajeDescuento": -0.24480369515011546,
      "PrecioDescuento": 327,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Comboleto 3",
      "Categoria": "Comboletos",
      "Descripcion": "3 boletos de taquilla + Maxicombo grupo chatbot (2 pal jum, 3 ref jumb) x $435",
      "PersonasObjetivo": 3,
      "VigenciaInicio": "01.10.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 3,
      "AlimentosIncluidos": "1 Maxicombo",
      "PrecioFull": 533,
      "PorcentajeDescuento": -0.1838649155722326,
      "PrecioDescuento": 435,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Palomitas para llevar mantequilla x $65",
      "Categoria": "Alimentos",
      "Descripcion": "1 Palomitas para llevar mantequilla x $65",
      "PersonasObjetivo": "1 ó más",
      "VigenciaInicio": "01.11.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Palomitas para llevar mantequilla",
      "PrecioFull": 110,
      "PorcentajeDescuento": -0.40909090909090906,
      "PrecioDescuento": 65,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 Frappes x $120",
      "Categoria": "Alimentos",
      "Descripcion": "2 frappes grandes x $120",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.11.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "2 Frappes grandes",
      "PrecioFull": 184,
      "PorcentajeDescuento": -0.34782608695652173,
      "PrecioDescuento": 120,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Maxicombo Micha Mix x $340",
      "Categoria": "Alimentos",
      "Descripcion": "1 Maxicombo Micha Mix x $340",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.11.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Maxicombo Micha Mix",
      "PrecioFull": 486,
      "PorcentajeDescuento": -0.3004115226337448,
      "PrecioDescuento": 340,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Combo bagui en pareja x $319",
      "Categoria": "Alimentos",
      "Descripcion": "1 Combo bagui en pareja x $319",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.11.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Combo bagui en pareja",
      "PrecioFull": 478,
      "PorcentajeDescuento": -0.33263598326359833,
      "PrecioDescuento": 319,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Comboleto 2",
      "Categoria": "Comboletos",
      "Descripcion": "2 boletos de taquilla + Nachos en pareja (1 Pal, 2 Ref Jumb, 1 Nachos) x $327",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.11.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 2,
      "AlimentosIncluidos": "1 CB Nachos en pareja",
      "PrecioFull": 433,
      "PorcentajeDescuento": -0.24480369515011546,
      "PrecioDescuento": 327,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Comboleto 3",
      "Categoria": "Comboletos",
      "Descripcion": "3 boletos de taquilla + Maxicombo grupo chatbot (2 pal jum, 3 ref jumb) x $435",
      "PersonasObjetivo": 3,
      "VigenciaInicio": "01.11.2025",
      "VigenciaFin": "30.11.2025",
      "Boletos": 3,
      "AlimentosIncluidos": "1 Maxicombo",
      "PrecioFull": 533,
      "PorcentajeDescuento": -0.1838649155722326,
      "PrecioDescuento": 435,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 ICEE x $130",
      "Categoria": "Alimentos",
      "Descripcion": "2 ICEE x $130",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.01.2026",
      "VigenciaFin": "31.01.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "2 ICEE",
      "PrecioFull": 204,
      "PorcentajeDescuento": -0.36274509803921573,
      "PrecioDescuento": 130,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 baguis x $150",
      "Categoria": "Alimentos",
      "Descripcion": "2 baguis x $150",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.01.2026",
      "VigenciaFin": "31.01.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "2 baguis",
      "PrecioFull": 280,
      "PorcentajeDescuento": -0.4642857142857143,
      "PrecioDescuento": 150,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Maxicombo Familiar x $320",
      "Categoria": "Alimentos",
      "Descripcion": "1 Maxicombo Familiar x $320",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.01.2026",
      "VigenciaFin": "31.01.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Maxicombo Familiar",
      "PrecioFull": 463,
      "PorcentajeDescuento": -0.3088552915766739,
      "PrecioDescuento": 320,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Combo crepa en pareja x $260",
      "Categoria": "Alimentos",
      "Descripcion": "1 Combo crepa en pareja x $260",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.01.2026",
      "VigenciaFin": "31.01.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Combo crepa en pareja",
      "PrecioFull": 320,
      "PorcentajeDescuento": -0.1875,
      "PrecioDescuento": 260,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 M&Ms Mega x $85",
      "Categoria": "Alimentos",
      "Descripcion": "2 M&Ms Mega x $85",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.04.2026",
      "VigenciaFin": "30.04.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "2 M&Ms Mega",
      "PrecioFull": 170,
      "PorcentajeDescuento": -0.5,
      "PrecioDescuento": 85,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 Frappes x $135",
      "Categoria": "Alimentos",
      "Descripcion": "2 frappes grandes x $135",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.04.2026",
      "VigenciaFin": "30.04.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "2 Frappes grandes",
      "PrecioFull": 194,
      "PorcentajeDescuento": -0.3041237113402062,
      "PrecioDescuento": 135,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Combo bagui en pareja x $329",
      "Categoria": "Alimentos",
      "Descripcion": "1 Combo bagui en pareja x $329",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.04.2026",
      "VigenciaFin": "30.04.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Combo bagui en pareja",
      "PrecioFull": 498,
      "PorcentajeDescuento": -0.3393574297188755,
      "PrecioDescuento": 329,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Palomitas para llevar mantequilla x $65",
      "Categoria": "Alimentos",
      "Descripcion": "1 Palomitas para llevar mantequilla x $65",
      "PersonasObjetivo": "1 ó más",
      "VigenciaInicio": "01.05.2026",
      "VigenciaFin": "31.05.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Palomitas para llevar mantequilla",
      "PrecioFull": 110,
      "PorcentajeDescuento": -0.40909090909090906,
      "PrecioDescuento": 65,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "2 baguis x $150",
      "Categoria": "Alimentos",
      "Descripcion": "2 baguis x $150",
      "PersonasObjetivo": 2,
      "VigenciaInicio": "01.05.2026",
      "VigenciaFin": "31.05.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "2 baguis",
      "PrecioFull": 280,
      "PorcentajeDescuento": -0.4642857142857143,
      "PrecioDescuento": 150,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    },
    {
      "Promocion": "Combo crepa en pareja x $279",
      "Categoria": "Alimentos",
      "Descripcion": "1 Combo crepa en pareja x $260",
      "PersonasObjetivo": "3 ó más",
      "VigenciaInicio": "01.05.2026",
      "VigenciaFin": "31.05.2026",
      "Boletos": 0,
      "AlimentosIncluidos": "1 Combo crepa en pareja",
      "PrecioFull": 352,
      "PorcentajeDescuento": -0.20738636363636365,
      "PrecioDescuento": 279,
      "RestriccionCine": "Todos los Cines, excepto formato VIP."
    }
  ],
  "promocionesTaquilla": [
    {
      "Mecanica": "Precio especial entre semana",
      "PersonasObjetivo": "1 ó más",
      "Promocion": "Lunes, Martes y Jueves, Entrada a precio especial: $45 2D y $55 3D",
      "VigenciaInicio": "2025-01-01",
      "VigenciaFin": "2025-10-31",
      "ClavePS": [
        1021269, 
      ],
    },
    {
      "Mecanica": "Precio Especial Baja Gas",
      "PersonasObjetivo": "1 ó más",
      "Promocion": "Entrada a precio especial de $49 al presentar ticket de consumo de gasolinera Baja Gas. Válido de lunes a viernes en formato 2D.",
      "VigenciaInicio": "2025-01-01",
      "VigenciaFin": "2025-09-02",
      "ClavePS": [
        1020353
      ],
    },
    {
      "Mecanica": "Precio Especial en Canales Digitales",
      "PersonasObjetivo": "1 ó más",
      "Promocion": "Entradas a precio especial de $30 al comprar en Canales Digitales (App, Web, Kioscos y Taquillas Automáticas). Válido de lunes a viernes en formato 2D.",
      "VigenciaInicio": "2025-01-01",
      "VigenciaFin": "2025-05-21",
      "ClavePS": [
        1020515, 
        1020454,
        1020561,
        1021051,
        1021264,
        1021204
      ],
    },
    {
      "Mecanica": "Entrada al 2x1 presentando ID Gob Edo de Qro",
      "PersonasObjetivo": 2,
      "Promocion": "Entrada al 2x1 al presentar la credencial de trabajador del Gobierno del Estado de Queretaro, adicional a su TCC, Válido de Lunes a viernes en funciones 2D y 3D, unicamente en POS",
      "VigenciaInicio": "2025-07-31",
      "VigenciaFin": "2025-11-19",
      "ClavePS": [
        1020309,
        1020945,
        1020047,
        1020528,
        1020080,
        1020560,
        1020672,
        1020915,
        1020444
      ]
    },
    {
      "Mecanica": "Entrada a precio especial",
      "PersonasObjetivo": 1,
      "Promocion": "Recibe una entrada a precio especial de $35 al presentar tu ticket de compra de \"BONPANE\" en la taquilla",
      "VigenciaInicio": "2025-01-01",
      "VigenciaFin": "2025-12-21",
      "ClavePS": [
        1021267
      ]
    },
    {
      "Mecanica": "Entrada al 2x1 presentando \"Gallobono\"",
      "PersonasObjetivo": 2,
      "Promocion": "Entrada al 2x1 al presentar la la membresia del Club Queretaro conocida como \"Gallobono\", Válido de Lunes a jueves en funciones 2D y 3D, unicamente en POS",
      "VigenciaInicio": "2025-08-01",
      "VigenciaFin": "2025-11-25",
      "ClavePS": [
        1020309,
        1020945,
        1020047,
        1020528,
        1020080,
        1020560,
        1020672,
        1020915,
        1020444
      ]
    }
  ]
};

export default PROMOTIONS;
